config/routes.rb
Rails.application.routes.draw do
  get 'admins/new'
  resources :admins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  before_save { self.email = email.downcase }
  VALNAME = /[0-9a-z_]{6,12}/i
  validates :name,  presence: true,length: {maximum: 12 },
             format: { with: VALNAME }

  VALEMAIL = /[0-9a-z]*@[0-9a-z]*\.[0-9a-z]*/i
  validates :email, presence: true, length: { maximum: 256 },
            format: { with: VALEMAIL }, uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { maximum: 256 }

  has_secure_password
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def new
  end

  def show
    @admin = Admin.find(params[:id])
    @admin_all = Admin.all
  end
  def index
    @admins = Admin.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admins/index.html.erb
<div>
<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
  </tr>
<% @admins.each do |admin| %>
  <tr>
    <td><%= admin.name %></td>
    <td><%= admin.email %></td>
  </tr>
<% end %>
</table>
</div>

app/views/admins/new.html.erb
<h1>Admins#new</h1>
<p>Find me in app/views/admins/new.html.erb</p>

app/views/admins/show.html.erb
<h1>Admins Profile</h1>
<div>
  <table>
    <tr>
      <th>Name</th>
      <td><%= @admin.name %></td>
    </tr>
    <tr>
      <th>Email</th>
      <td><%= @admin.email %></td>
    </tr>
</table>
<%= link_to "Edit profile", '#' %>
</div>

<div>
  <%= link_to "View all Admins", admins_path %>
  <br>
  <%= link_to "View all Rooms", '#' %>
  <br>
  <%= link_to "View all Library Members", '#' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LibRMBookingApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>